version: '3.8'

services:
  app:
    build: .
    image: softirest:latest
    container_name: softirest-container  # Bu yerda konteyner nomi aniq belgilangan
    ports:
      - "8000:8000"  # 8080 porti hostda, 8000 porti konteynerda
    volumes:
      - .:/app  # Hozirgi papkadan /app ga bog'lash
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: postgres-container  # Bu yerda konteyner nomi aniq belgilangan
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # 5432 porti hostda, 5432 porti konteynerda
    volumes:
      - ./data:/var/lib/postgresql/data  # Hozirgi papkadan /var/lib/postgresql/data ga bog'lash
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
 